// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tptmgnhhkjggkuivsjtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdG1nbmhoa2pnZ2t1aXZzanRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTkxNTUsImV4cCI6MjA2NDU5NTE1NX0.DmGkDpdtvZhjCfgb72lCXiou1GyUttdJrn1Sr3bcm98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);